export enum EnvConfig {
	JWT_SECRET = 'JWT_SECRET',
	JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
	DB_TYPE = 'DB_TYPE',
	DB_HOST = 'DB_HOST',
	DB_PORT = 'DB_PORT',
	DB_USERNAME = 'DB_USERNAME',
	DB_PASSWORD = 'DB_PASSWORD',
	DB_NAME = 'DB_NAME'
}